### ISSUE TITLE
New gateway chart do not take global params into account

### ISSUE THREAD

**Issue by boeboe** [tetratelabs/helm-charts#2]
**Problem description:**

When deploying `base`, `istiod` and `gateway` charts with `--set global.tag="1.14.4-tetratefips-v0-distroless"` option, I noticed that my gateway pods were still using `proxyv2:1.14.4-tetrate-multiarch-v1`.

The reason is that in the new `gateway` charts (that replace the `istio-ingress` and `istio-egress` charts) do not access global values within the deployment template and value.yaml.

This problem also exists upstream.

**Impact:**

Not able to deploy a full fips compliant stack using helm repo.

**Comment by psbrar99** [comment]
@boeboe : As you mentioned, the gateway chart has no access to global values (.values.global.proxy.image), infact this is not configurable for gateway charts. This is by design and intentionally set to auto. The intent is to use the same sidecar proxy behaviour, governed by sidecar injector config map.
Using the same mechanisms as [Istio sidecar injection](https://istio.io/latest/docs/setup/additional-setup/sidecar-injection/#automatic-sidecar-injection), the Envoy proxy configuration for gateways can similarly be auto-injected. 

To workaround this  either we can
- --set global.tag = <distoless> during control-plane installation
- patch istio-sidecar-injector configmpa to update the tag. smthng like this 
`kubectl get cm  -n istio-system istio-sidecar-injector -o yaml | sed  -e  "s/1.14.5-tetrate-multiarch-v2/1.14.5-tetrate-multiarch-v2-distroless/g" | kubectl replace -f -`

We can also try editing the helm charts for gateway in case both the options are not available.

**Comment by boeboe** [comment]
From the documentation

> image: auto Information
> The image used by the chart, auto, may be unintuitive. This exists because the pod spec will be automatically populated at runtime, using the same mechanism as Sidecar Injection. This allows the same configurations and lifecycle to apply to gateways as sidecars.
> 
> Note: this does mean that the namespace the gateway is deployed in must not have the istio-injection=disabled label. See  for more info.

I took a look at the code to see where the magic happened:

**manifests/charts/istio-control/istio-discovery/files/injection-template.yaml**

```yaml
spec:
  initContainers: ...
  containers:
  - name: istio-proxy
  {{- if contains "/" (annotation .ObjectMeta `sidecar.istio.io/proxyImage` .Values.global.proxy.image) }}
    image: "{{ annotation .ObjectMeta `sidecar.istio.io/proxyImage` .Values.global.proxy.image }}"
  {{- else }}
    image: "{{ .ProxyImage }}"
  {{- end }}
```


**manifests/charts/istio-control/istio-discovery/files/gateway-injection-template.yaml**

```yaml
spec:
  containers:
  - name: istio-proxy
  {{- if contains "/" .Values.global.proxy.image }}
    image: "{{ annotation .ObjectMeta `sidecar.istio.io/proxyImage` .Values.global.proxy.image }}"
  {{- else }}
    image: "{{ .ProxyImage }}"
  {{- end }}
```

Should these two blocks not contain something like this instead (I fail to find a reference to the `.ProxyImage` being set, as mentioned above in case `.Values.global.proxy.image` does not contain a `/`:

```yaml
spec:
  containers:
  - name: istio-proxy
  {{- if contains "/" .Values.global.proxy.image }}
    image: "{{ annotation .ObjectMeta `sidecar.istio.io/proxyImage` .Values.global.proxy.image }}"
  {{- else }}
    image: "{{ .Values.global.hub }}/{{ .Values.global.proxy.image | default "proxyv2" }}:{{ .Values.global.tag }}"
  {{- end }}
````
